"""
This module contains four napari widgets declared in
different ways:

- a pure Python function flagged with `autogenerate: true`
    in the plugin manifest. Type annotations are used by
    magicgui to generate widgets for each parameter. Best
    suited for simple processing tasks - usually taking
    in and/or returning a layer.
- a `magic_factory` decorated function. The `magic_factory`
    decorator allows us to customize aspects of the resulting
    GUI, including the widgets associated with each parameter.
    Best used when you have a very simple processing task,
    but want some control over the autogenerated widgets. If you
    find yourself needing to define lots of nested functions to achieve
    your functionality, maybe look at the `Container` widget!
- a `magicgui.widgets.Container` subclass. This provides lots
    of flexibility and customization options while still supporting
    `magicgui` widgets and convenience methods for creating widgets
    from type annotations. If you want to customize your widgets and
    connect callbacks, this is the best widget option for you.
- a `QWidget` subclass. This provides maximal flexibility but requires
    full specification of widget layouts, callbacks, events, etc.

References:
- Widget specification: https://napari.org/stable/plugins/building_a_plugin/guides.html#widgets
- magicgui docs: https://pyapp-kit.github.io/magicgui/

Replace code below according to your needs.
"""

from cProfile import label
from hmac import new
from magicgui import magic_factory
from magicgui.widgets import CheckBox, Container, create_widget
import napari
import napari.utils
import napari.utils.notifications
from qtpy.QtWidgets import QHBoxLayout, QVBoxLayout, QPushButton, QCheckBox, QWidget, QLabel, QDoubleSpinBox, QTabWidget, QComboBox
from qtpy.QtCore import Qt
import brimfile as brim
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvas
import numpy as np



# if we want even more control over our widget, we can use
# magicgui `Container`
class ShowSpectrum(Container):
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self._viewer = viewer

        # matplotlib figure
        self.fig, self.ax = plt.subplots()
        self.fig.set_layout_engine('constrained')
        self.fig.patch.set_alpha(0)
        self.ax.set_xlabel('Frequency []', color='white')
        self.ax.set_ylabel('PSD', color='white')
        self.ax.tick_params(axis='x', colors='white')
        self.ax.tick_params(axis='y', colors='white')
        self.ax.yaxis.label.set_color('white')
        self.ax.xaxis.label.set_color('white')
        self.ax.set_ylim(0,1)   # 37 41 49
        self.spectrum_ymax = 0
        self.spectrum_ymin = 1E6

        # connect your own callbacks
        self._connect_mouse_events()

        # Tabs - add different widgets
        tabs = QTabWidget()
        tabs.setTabPosition(QTabWidget.TabPosition.North)
        tabs.setMovable(True)
        tabs.setDocumentMode(True)
        tabs.tabBar().setDrawBase(False)
        tabs.setStyleSheet("""
            QTabBar::tab {
                background: #3F4852;         /* Simple background color */
                color: #D1D2D4;                 /* Text color */
                padding: 6px 16px;
                margin-right: 2px;           /* Space between tabs */
                min-width: 80px;
                border-bottom: none; /* remove the dividing line */
                border: none;
            }
            QTabBar::tab:selected {
                background: #58626D;         /* Background for selected tab */
                color: #D1D2D4;
            }
            QTabBar::tab:!selected {
                background: #3F4852;         /* No shading for unselected tabs */
            }
            QTabBar {
                alignment: left;
                qproperty-drawBase: 0;
                background: transparent;
            } 
            QTabWidget::pane {
                border: none;
                background: transparent;
            }
            """)

        # Spectrum Plotting tab
        self._autoscale_checkbox = QCheckBox(text = 'Autoscale y-axis')
        self._autoscale_checkbox.setChecked(False)
        self._autoscale_checkbox.stateChanged.connect(self._reset_autoscale)

        spectrum_plotting_widget = QWidget()
        spectrum_plotting_layout = QVBoxLayout()
        spectrum_plotting_widget.setLayout(spectrum_plotting_layout)
        spectrum_plotting_layout.addWidget(FigureCanvas(self.fig))
        spectrum_plotting_layout.addWidget(self._autoscale_checkbox)

        # Spectral Image tab
        spectral_image_widget = QWidget()
        spectral_image_layout = QVBoxLayout()
        spectral_image_layout.setAlignment(Qt.AlignTop)
        spectral_image_widget.setLayout(spectral_image_layout)

        self._spectral_image_text = QLabel(text='Create a spectral image by integrating the spectrum in a frequency range for each pixel.\nSelect the frequency range and click the button to create the spectral image.')
        self._spectral_image_text.setAlignment(Qt.AlignCenter)
        self._spectral_image_text.setWordWrap(True)
        self._num_label1 = QLabel("Lower bound")
        self._num_field1 = QDoubleSpinBox()
        self._num_field1.setRange(-30, 30)
        self._num_field1.setValue(-30)
        self._num_field1.setSingleStep(0.1)
        self._num_field1.setDecimals(2)
        self._num_field1.setSuffix(" GHz")
        self._num_field1.setMaximumWidth(150)

        self._num_label2 = QLabel("Upper bound")
        self._num_field2 = QDoubleSpinBox()
        self._num_field2.setRange(-30, 30)
        self._num_field2.setValue(30)
        self._num_field2.setSingleStep(0.1)
        self._num_field2.setDecimals(2)
        self._num_field2.setSuffix(" GHz")
        self._num_field2.setMaximumWidth(150)

        self._create_btn = QPushButton("Create spectral image")
        self._create_btn.clicked.connect(self._on_create_spectral_image)

        spectral_image_layout.addWidget(self._spectral_image_text)
        spectral_image_layout.addWidget(self._num_label1)
        spectral_image_layout.addWidget(self._num_field1)
        spectral_image_layout.addWidget(self._num_label2)
        spectral_image_layout.addWidget(self._num_field2)
        spectral_image_layout.addWidget(self._create_btn)
        
        # Regional Spectra tab
        # Based on a labels layer, create average spectra and shift histograms for each present label
        labels_widget = QWidget()
        labels_layout = QVBoxLayout()
        labels_widget.setLayout(labels_layout)

        labels_text = QLabel(text='Region-based analysis of Brillouin images. Select labels layer from list. Analysis is then applied to active Brimfile layer.\n Show average spectrum, explore quantity at reagion')
        labels_text.setAlignment(Qt.AlignCenter)
        labels_text.setWordWrap(True)
        labels_layout.addWidget(labels_text)

        labels_selection_layout = QHBoxLayout()
        labels_layout.addLayout(labels_selection_layout)

        self._labels_combobox = QComboBox()
        # If new selection made, check if confirms.
        labels_new_button = QPushButton("Create new labels layer")
        labels_new_button.clicked.connect(self._create_labels_layer)
        labels_selection_layout.addWidget(self._labels_combobox)
        labels_selection_layout.addWidget(labels_new_button)

        # Add analyse button - then check if layer is eligible?
        labels_analyse_button = QPushButton("Plot average spectra")
        labels_analyse_button.clicked.connect(self._plot_labels_spectrum)
        labels_layout.addWidget(labels_analyse_button)

        # Add Widgets to tab
        tabs.addTab(spectrum_plotting_widget, "Plot Spectrum at Pixel")
        tabs.addTab(spectral_image_widget, "Create Spectral Image")
        tabs.addTab(labels_widget, "Regional Spectra Analysis")

        self._update_labels_combobox()
        self._viewer.layers.selection.events.changed.connect(self._update_labels_combobox)
        self._viewer.layers.events.inserted.connect(self._update_labels_combobox)
        self._viewer.layers.events.removed.connect(self._update_labels_combobox)

        # Add Tabs widget to Napari widget
        self.native.layout().addWidget(tabs)

    def _create_labels_layer(self):
        layer = self._viewer.layers.selection.active
        if layer is None:
            return
        if (('is_brimfile', True) not in layer.metadata.items()):
            napari.utils.notifications.show_info("A brimfile layer needs to be selected to create a labels layer.")
            return 
        # Create a new labels layer with the same shape as the active layer
        labels_data = np.zeros(layer.data.shape, dtype=np.uint8)
        self._viewer.add_labels(
            labels_data, 
            name=f"Labels for {layer.name}",
            scale=layer.scale,
            units=layer.units,
            )
    
    def _update_labels_combobox(self):
        # get all labels layers in the viewer and add to combobox
        self._labels_combobox.clear()
        active_layer = self._viewer.layers.selection.active
        if active_layer is None:
            return
        if (('is_brimfile', True) not in active_layer.metadata.items()):
            return  # ignore all other layers
        for layer in self._viewer.layers:
            if isinstance(layer, napari.layers.Labels) and (layer.data.shape*layer.scale == active_layer.data.shape*active_layer.scale).all(): 
                self._labels_combobox.addItem(layer.name)

    def _on_create_spectral_image(self):
        layer = self._viewer.layers.selection.active
        if (layer is None) or layer.visible == False:
                return
        # Check metadata attribute
        if (('is_brimfile', True) not in layer.metadata.items()):
            napari.utils.notifications.show_info("A brimfile layer needs to be selected to create a spectral image.")
            return  # ignore all other layers
        
        file = layer.metadata['brimfile']
        # go through every pixel and get sum intensity, then add to spectral image
        # get baseline from Python fit to substract
        image_PSD = file.get_data(layer.metadata['Data_group']).get_PSD_as_spatial_map() #[0] is intensities, [1] is frequencies
        image_offset = file.get_data(layer.metadata['Data_group']).get_analysis_results().get_image(brim.Data.AnalysisResults.Quantity.Offset)[0][:,:,:,np.newaxis]
        image_ampl = image_PSD[0] - image_offset
        image_mask = (image_PSD[1] >= self._num_field1.value()) & (image_PSD[1] <= self._num_field2.value())
        image_ampl = image_ampl * image_mask
        spectral_img = np.sum(image_ampl, axis=-1)
        
        try:
            self._viewer.add_image(
                spectral_img, 
                name=f'Spectral image from {self._num_field1.value()} to {self._num_field2.value()} GHz',
                scale=layer.scale,
                units=layer.units,
                )
        except Exception:
            print("Failed to add spectral image layer")

    def _connect_mouse_events(self):
        def on_click(viewer, event):
            layer = viewer.layers.selection.active
            if layer is None:
                return
            # Check metadata attribute
            if (('is_brimfile', True) not in layer.metadata.items()):
                return  # ignore all other layers
            
            dragged = False
            yield
            # on move
            while event.type == 'mouse_move':
                dragged = True
                yield
            # on release
            if dragged:
                return
            else:
                # Now handle the click
                coord = layer.world_to_data(event.position) 
                coord = np.round(np.array(coord)).astype(int)
                self._load_spectrum(tuple(coord), layer)

        # Attach callback to the viewer (not to each layer)
        self._viewer.mouse_drag_callbacks.append(on_click)

    def _reset_autoscale(self):
        self.spectrum_ymax = 0
        self.spectrum_ymin = 1E6

    def _load_spectrum(self, coord, image_layer):
        file = image_layer.metadata['brimfile']
        if image_layer.visible == False:
            return
        # check if coords are within image
        image_shape = image_layer.data.shape
        for i in range(len(image_shape)):
            if (coord[i] < 0) | (coord[i] > image_shape[i]-1):
                return

        # plot spectrum
        spectrum = file.get_data(image_layer.metadata['Data_group']).get_spectrum_in_image(coord)
        spectrum_sorted = np.array([spectrum[0], spectrum[1]])[:,np.lexsort(np.array([spectrum[0], spectrum[1]]))]
        spectrum_sorted = spectrum_sorted[:,np.logical_not(np.isnan(spectrum_sorted[1]))]
        if self.spectrum_ymax < max(spectrum_sorted[0]):
            self.spectrum_ymax = max(spectrum_sorted[0])
        if self.spectrum_ymin > min(spectrum_sorted[0]):
            self.spectrum_ymin = min(spectrum_sorted[0])
        self.ax.clear()
        # Check if part of the spectrum is missing
        frequ_diffs = np.diff(spectrum_sorted[1])
        frequ_spacing = np.median(frequ_diffs)
        frequ_jumps = np.where(frequ_diffs > 2*frequ_spacing)[0]
        if len(frequ_jumps) == 0:
            self.ax.plot(spectrum[1], spectrum[0], color = "#454B50")
        else: # split 
            frequ_jumps = np.concat([[0],frequ_jumps+1,[len(spectrum_sorted[1,:])]])      # 0 i, i j, j -1
            for i in range(len(frequ_jumps)-1):
                self.ax.plot(
                    spectrum_sorted[1,frequ_jumps[i]:frequ_jumps[i+1]], 
                    spectrum_sorted[0,frequ_jumps[i]:frequ_jumps[i+1]], 
                    color = "#252931", 
                    lw = 2)
        self.ax.set_xlabel('Frequency [{}]'.format(spectrum[3]), color='white')
        self.ax.set_ylabel('PSD', color='white')
        if not self._autoscale_checkbox.isChecked():
            self.ax.set_ylim(self.spectrum_ymin, self.spectrum_ymax)
        self.ax.set_title('Spectrum of ' + image_layer.name + '\nat pixel [{},{},{}]'.format(coord[0],coord[1],coord[2]), color='White', fontsize = 12)
        self.fig.canvas.draw()

    def _plot_labels_spectrum(self): #CHECK!!
        napari.utils.notifications.show_error("Function not implemented yet.")
        return 
    
        # get all pixels with label
        layer = self._viewer.layers[self._labels_combobox.currentText()]
        mask = layer.data == label
        if np.sum(mask) == 0:
            napari.utils.notifications.show_info(f"No pixels with label {label} found in the selected labels layer")
            return
        # get spectra for all pixels and average
        file = None
        for l in self._viewer.layers:
            if (('is_brimfile', True) in l.metadata.items()) and (l.data.shape*layer.scale == l.data.shape*l.scale).all():
                file = l.metadata['brimfile']
                break
        if file is None:
            napari.utils.notifications.show_info("No brimfile layer found with matching shape and scale to the selected labels layer")
            return
        
        spectra = []
        for coord in np.argwhere(mask):
            spectrum = file.get_data(layer.metadata['Data_group']).get_spectrum_in_image(tuple(coord))
            spectra.append(spectrum[0])
        avg_spectrum = np.mean(spectra, axis=0)
        # plot average spectrum
        self.ax.clear()
        self.ax.plot(spectrum[1], avg_spectrum, color = "#252931", lw = 2)
        self.ax.set_xlabel('Frequency [{}]'.format(spectrum[3]), color='white')
        self.ax.set_ylabel('PSD', color='white')
        self.ax.set_title(f'Average spectrum of label {label} in {layer.name}', color='White', fontsize = 12)
        self.fig.canvas.draw()

    