"""
This module contains four napari widgets declared in
different ways:

- a pure Python function flagged with `autogenerate: true`
    in the plugin manifest. Type annotations are used by
    magicgui to generate widgets for each parameter. Best
    suited for simple processing tasks - usually taking
    in and/or returning a layer.
- a `magic_factory` decorated function. The `magic_factory`
    decorator allows us to customize aspects of the resulting
    GUI, including the widgets associated with each parameter.
    Best used when you have a very simple processing task,
    but want some control over the autogenerated widgets. If you
    find yourself needing to define lots of nested functions to achieve
    your functionality, maybe look at the `Container` widget!
- a `magicgui.widgets.Container` subclass. This provides lots
    of flexibility and customization options while still supporting
    `magicgui` widgets and convenience methods for creating widgets
    from type annotations. If you want to customize your widgets and
    connect callbacks, this is the best widget option for you.
- a `QWidget` subclass. This provides maximal flexibility but requires
    full specification of widget layouts, callbacks, events, etc.

References:
- Widget specification: https://napari.org/stable/plugins/building_a_plugin/guides.html#widgets
- magicgui docs: https://pyapp-kit.github.io/magicgui/

Replace code below according to your needs.
"""
from turtle import color
from typing import TYPE_CHECKING

from magicgui import magic_factory
from magicgui.widgets import CheckBox, Container, create_widget
from qtpy.QtWidgets import QHBoxLayout, QPushButton, QWidget
from skimage.util import img_as_float
import brimfile as brim
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvas
import numpy as np

if TYPE_CHECKING:
    import napari




# if we want even more control over our widget, we can use
# magicgui `Container`
class ShowSpectrum(Container):
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self._viewer = viewer

        # matplotlib figure
        self.fig, self.ax = plt.subplots()
        self.fig.set_layout_engine('constrained')
        self.fig.patch.set_alpha(0)
        self.ax.set_xlabel('Frequency []', color='white')
        self.ax.set_ylabel('PSD', color='white')
        self.ax.tick_params(axis='x', colors='white')
        self.ax.tick_params(axis='y', colors='white')
        self.ax.yaxis.label.set_color('white')
        self.ax.xaxis.label.set_color('white')
        self.ax.set_ylim(0,1)
        self.spectrum_ymax = 0
        self.spectrum_ymin = 1E6

        # connect your own callbacks
        self._connect_mouse_events()
        self.native.layout().addWidget(FigureCanvas(self.fig))

        self._invert_checkbox = CheckBox(text="Autoscale y-axis")
        self._invert_checkbox.changed.connect(self._reset_autoscale)

        self.extend(
            [
                self._invert_checkbox,
            ]
        )

    def _connect_mouse_events(self):
        def on_click(viewer, event):
            layer = viewer.layers.selection.active
            if layer is None:
                return
            # Check metadata attribute
            if (('is_brimfile', True) not in layer.metadata.items()):
                return  # ignore all other layers
            
            dragged = False
            yield
            # on move
            while event.type == 'mouse_move':
                dragged = True
                yield
            # on release
            if dragged:
                return
            else:
                # Now handle the click
                coord = layer.world_to_data(event.position) 
                coord = np.round(np.array(coord)).astype(int)
                self._load_spectrum(tuple(coord), layer)

        # Attach callback to the viewer (not to each layer)
        self._viewer.mouse_drag_callbacks.append(on_click)

    def _reset_autoscale(self):
        self.spectrum_ymax = 0
        self.spectrum_ymin = 1E6

    def _load_spectrum(self, coord, image_layer):
        file = image_layer.metadata['brimfile']
        if image_layer.visible == False:
            return
        # check if coords are within image
        image_shape = image_layer.data.shape
        for i in range(len(image_shape)):
            if (coord[i] < 0) | (coord[i] > image_shape[i]-1):
                return

        # plot spectrum
        spectrum = file.get_data(image_layer.metadata['Data_group']).get_spectrum_in_image(coord)
        spectrum_sorted = np.array([spectrum[0], spectrum[1]])[:,np.lexsort(np.array([spectrum[0], spectrum[1]]))]
        spectrum_sorted = spectrum_sorted[:,np.logical_not(np.isnan(spectrum_sorted[1]))]
        if self.spectrum_ymax < max(spectrum_sorted[0]):
            self.spectrum_ymax = max(spectrum_sorted[0])
        if self.spectrum_ymin > min(spectrum_sorted[0]):
            self.spectrum_ymin = min(spectrum_sorted[0])
        self.ax.clear()
        # Check if part of the spectrum is missing
        frequ_diffs = np.diff(spectrum_sorted[1])
        frequ_spacing = np.median(frequ_diffs)
        frequ_jumps = np.where(frequ_diffs > 2*frequ_spacing)[0]
        if len(frequ_jumps) == 0:
            self.ax.plot(spectrum[1], spectrum[0], color = "#454B50")
        else: # split 
            frequ_jumps = np.concat([[0],frequ_jumps+1,[len(spectrum_sorted[1,:])]])      # 0 i, i j, j -1
            for i in range(len(frequ_jumps)-1):
                self.ax.plot(spectrum_sorted[1,frequ_jumps[i]:frequ_jumps[i+1]], spectrum_sorted[0,frequ_jumps[i]:frequ_jumps[i+1]], color = "#454B50")
        self.ax.set_xlabel('Frequency [{}]'.format(spectrum[3]), color='white')
        self.ax.set_ylabel('PSD', color='white')
        if self._invert_checkbox.value == False:
            self.ax.set_ylim(self.spectrum_ymin, self.spectrum_ymax)
        self.ax.set_title('Spectrum of ' + image_layer.name + '\nat pixel [{},{},{}]'.format(coord[0],coord[1],coord[2]), color='White', fontsize = 12)
        self.fig.canvas.draw()
